export class MutationTypes {

  public static LOGIN_USER = 'LOGIN_USER';
  public static LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
  public static LOGIN_REQUESTED = 'LOGIN_REQUESTED';
  public static LOGIN_FAILED = 'LOGIN_FAILED';
  public static LOGOUT_USER = 'LOGOUT_USER';

  public static FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
  public static FORGOT_PASSWORD_SUCCEEDED = 'FORGOT_PASSWORD_SUCCEEDED';
  public static FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

  public static CONFIRM_PASSWORD_REQUEST = 'CONFIRM_PASSWORD_REQUEST';
  public static CONFIRM_PASSWORD_SUCCEEDED = 'CONFIRM_PASSWORD_SUCCEEDED';
  public static CONFIRM_PASSWORD_FAILED = 'CONFIRM_PASSWORD_FAILED';

  public static SUBMIT_CONTACT_INFO = 'SUBMIT_CONTACT_INFO';
  public static GET_CONTACT_INFO = 'GET_CONTACT_INFO';
  // public static GET_PERSON_INFO = 'GET_PERSON_INFO';

  public static UPLOAD_FILE = 'UPLOAD_FILE';
  public static GET_PERSON_INFO = 'GET_PERSON_INFO';
  public static UPDATE_PERSON_INFO = 'UPDATE_PERSON_INFO';

  public static GET_CORPORA = 'GET_CORPORA';

  public static STRIPE_A1 = 'STRIPE_A1';

  public static GET_CLIENT_NAME_REQUEST = 'GET_CLIENT_NAME_REQUEST';

  public static CREATE_CORPUS_REQUEST = 'CREATE_CORPUS_REQUEST';

  public static CREATE_ACCOUNT = 'CREATE_ACCOUNT';

  public static GET_TOP_LINE = 'GET_TOP_LINE';

  public static EXPORT_CONTACTS = 'EXPORT_CONTACTS';

  public static GET_BILLING_INFO = 'GET_BILLING_INFO';

  public static STRIPE_CHECKOUT = 'STRIPE_CHECKOUT';

  public static GET_CLIENT_FILE_FILTERS = 'GET_CLIENT_FILE_FILTERS';
}
