export class MutationTypes {
  public static LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
  public static LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
  public static LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
  
  public static LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';

  public static REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';

  public static CONFIRM_USER_REQUEST = 'CONFIRM_USER_REQUEST';

  public static GET_COMPANY_NAME_REQUEST = 'GET_COMPANY_NAME_REQUEST';
  public static CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';

  public static FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
  public static FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
  public static FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

  public static CONFIRM_PASSWORD_REQUEST = 'CONFIRM_PASSWORD_REQUEST';
  public static CONFIRM_PASSWORD_SUCCESS = 'CONFIRM_PASSWORD_SUCCESS';
  public static CONFIRM_PASSWORD_FAILURE = 'CONFIRM_PASSWORD_FAILURE';

  public static GET_CLIENT_NAME_REQUEST = 'GET_CLIENT_NAME_REQUEST';

  public static GET_CONTACT_INFO_REQUEST = 'GET_CONTACT_INFO_REQUEST';
  public static SUBMIT_CONTACT_INFO_REQUEST = 'SUBMIT_CONTACT_INFO_REQUEST';

  public static UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';

  public static GET_PERSON_INFO_REQUEST = 'GET_PERSON_INFO_REQUEST';
  public static UPDATE_PERSON_INFO_REQUEST = 'UPDATE_PERSON_INFO_REQUEST';

  public static GET_CORPORA_REQUEST = 'GET_CORPORA_REQUEST';
  
  public static CREATE_CORPUS_REQUEST = 'CREATE_CORPUS_REQUEST';

  public static GET_TOP_LINE_REQUEST = 'GET_TOP_LINE_REQUEST';

  public static EXPORT_CONTACTS_REQUEST = 'EXPORT_CONTACTS_REQUEST';
  public static EXPORT_CONTACTS_CAMPAIGN_RECOMMENDATION_REQUEST = 'EXPORT_CONTACTS_CAMPAIGN_RECOMMENDATION_REQUEST';

  public static GET_CLIENT_FILE_FILTERS_REQUEST = 'GET_CLIENT_FILE_FILTERS_REQUEST';

  public static GET_BILLING_INFO_REQUEST = 'GET_BILLING_INFO_REQUEST';

  public static STRIPE_CHECKOUT_REQUEST = 'STRIPE_CHECKOUT_REQUEST';

  public static GET_CAMPAIGN_RECOMMENDATION = 'GET_CAMPAIGN_RECOMMENDATION';
}
